version: '3'

services:
    mysql:
        image: 'mysql:8.0'
        container_name: calendar_smart_db_8
        ports:
            - ${DATABASE_PORT}:3306
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
